LPTabState=function(){var j={},e=function(a){this.tabID=a.tabID;this.domain=lp_gettld_url(a.tabURL);this.sites=[];this.acccountsVersion=-1};e.prototype.getSites=function(){if(this.acccountsVersion!==g_local_accts_version){this.sites=[];for(var a in g_sites){var b=g_sites[a];lp_gettld_url(b.url)===this.domain&&this.sites.push(b)}this.acccountsVersion=g_local_accts_version}return this.sites};var k,h=function(a,b,c){var d=c[b];"undefined"===typeof d?c[b]={field:a,count:1}:++d.count};k=function(a,b){a.textFieldsByValue=
{};a.passwordsByValue={};a.textFieldsByType={};a.fields.forEach(function(b){"password"===b.type?h(b,b.value,a.passwordsByValue):(h(b,b.value,a.textFieldsByValue),h(b,b.type,a.textFieldsByType))});a.uniqueTextValues=Object.keys(a.textFieldsByValue);a.uniquePasswords=Object.keys(a.passwordsByValue);a.inFrame=!b.top};e.prototype.processPasswordSubmit=function(a,b){this.formData=null;a&&(k(a,b),this.processLoginForm(a)||this.processPasswordChangeForm(a)||this.processCreateAccountForm(a)||a.passwordsByValue.hasOwnProperty(this.generatedPassword)?
(this.formData=a,this.generatedPassword&&(this.password=this.generatedPassword)):this.clear())};e.prototype.processUsernameSubmit=function(a){this.usernameField=a};e.prototype.processPasswordChangeForm=function(a){a.passwordChangeForm=!1;if(2===a.uniquePasswords.length){if(a.uniquePasswords.forEach(function(b){2===a.passwordsByValue[b].count?(this.password=b,a.passwordChangeForm=!0):this.originalPassword=b},this),!a.passwordChangeForm){var b=l(this.getSites(),a.uniquePasswords);b&&(a.passwordChangeForm=
!0,this.password=a.uniquePasswords[0]===b?a.uniquePasswords[1]:a.uniquePasswords[0],this.originalPassword=b)}}else 2===a.fields.length&&1===a.uniquePasswords.length&&(a.passwordChangeForm=!0,this.password=a.uniquePasswords[0]);a.passwordChangeForm&&(this.formData=a);return a.passwordChangeForm};var l=function(a,b){b=[].concat(b);for(var c=0;c<a.length;++c){var d=b.indexOf(lpmdec_acct(a[c].password,!0,a[c],g_shares));if(-1<d)return b[d]}return null};e.prototype.processLoginForm=function(a){a.loginForm=
!1;if(2===a.fields.length&&1===a.uniqueTextValues.length&&1===a.uniquePasswords.length)a.loginForm=!0,this.username=a.uniqueTextValues[0],this.password=a.uniquePasswords[0],a.fields.forEach(function(a){a.value===this.username&&(this.usernameField=a)},this);else if(1===a.fields.length&&this.usernameField){var b=a.fields[0];"password"===b.type&&(a.loginForm=!0,this.username=this.usernameField.value,this.password=b.value,a.fields.push(this.usernameField))}a.loginForm&&(this.formData=a);return a.loginForm};
var g=function(a,b){if(a){b=[].concat(b);for(var c=0;c<b.length;++c)if(-1<a.indexOf(b[c]))return!0}return!1};e.prototype.processCreateAccountForm=function(a){a.createAccountForm=!1;if(0<a.uniqueTextValues.length&&0<a.uniquePasswords.length){var b;if(this.usernameField)b=this.usernameField.value;else{var c=null;if(1===a.uniqueTextValues.length)c=a.uniqueTextValues[0];else{for(b in g_sites)if(-1<a.uniqueTextValues.indexOf(g_sites[b].unencryptedUsername)){c=g_sites[b].unencryptedUsername;break}c||a.uniqueTextValues.forEach(function(b){1<
a.textFieldsByValue[b].count&&(c=b)});c||a.uniqueTextValues.forEach(function(b){var d=a.textFieldsByValue[b].field;if(g(d.attributes.name,"user")||g(d.id,"user"))c=b});!c&&(a.textFieldsByType.email&&1===a.textFieldsByType.email.count)&&(c=a.textFieldsByType.email.field.value)}b=c}this.username=b;var d=null;1===a.uniquePasswords.length?d=a.uniquePasswords[0]:(a.uniquePasswords.forEach(function(b){1<a.passwordsByValue[b].count&&(d=b)}),d||a.uniquePasswords.forEach(function(b){var c=a.passwordsByValue[b].field,
e=["pw","pass"];if(g(c.attributes.name,e)||g(c.id,e))d=b}));this.password=d;if(this.username||this.password)a.createAccountForm=!0,this.formData=a}return a.createAccountForm};e.prototype.getMatchingSites=function(){var a=this,b=a.getSites();a.username?b=b.filter(function(b){return b.unencryptedUsername===a.username}):(a.originalPassword&&(b=b.filter(function(b){return lpmdec_acct(b.password,!0,b,g_shares)===a.originalPassword})),0===b.length&&(b=a.getSites()));return b};e.prototype.getSiteNotificationData=
function(a){var b=this.getFormSubmissionTabState(),c={formData:b.formData,formExists:b.formExists};if(b.formData&&(b.formData.basicAuthentication||!b.formExists)){a=b.getMatchingSites();if(l(a,b.password))return b.clear(),{};c.matchingSites=a.map(function(a){return a.aid});c.defaultData={url:b.formData.basicAuthentication||b.formData.loginForm?b.formData.url:hostof(b.formData.url),name:b.domain,unencryptedUsername:b.username,group:siteCats[b.domain],basic_auth:b.realm?"1":"0",realm:b.realm};c.dialogData=
{password:b.password};b.formData.loginForm&&(c.dialogData.fields=[],b.formData.fields.forEach(function(a){c.dialogData.fields.push({name:a.attributes.name||a.id,type:a.type,value:a.value,formname:b.formData.formname||""})}));c.generatedPassword=b.generatedPassword?!0:!1}else b.generatedPassword?b.generatedURL!==a.tabURL&&(c.defaultData={url:b.generatedURL,name:b.domain,unencryptedUsername:b.username,group:siteCats[b.domain]},c.dialogData={password:b.generatedPassword},c.matchingSites=b.getMatchingSites().map(function(a){return a.aid}),
c.generatedPassword=b.generatedPassword?!0:!1):b.clear();return c};e.prototype.getFormSubmissionTabState=function(){for(var a=this;a;){if(a.formData||a.generatedPassword)return a;a=a.previousTabState}return this};e.prototype.getSiteNotification=function(a,b){var c=this;if(c.formData&&!c.formData.basicAuthentication){var d=LPTabs.get({tabID:this.tabID});c.formExists=!1;var e=function(){if(!c.formExists&&!(c.username||0===c.getSites().length)){var e=a.callback,f=c.getSites().map(function(a){return a.unencryptedUsername});
d.forEachWindow({each:function(a,b){return a.LPContentScriptTools.findText(f,function(a){a&&(c.username=a);b()})},done:function(){e(c.getSiteNotificationData(b))}})}else a.callback(c.getSiteNotificationData(b))};a.source?d.getFrame(a.source.frameID).LPSiteNotification.formExists(c.formData,function(a){c.formExists=a;e()}):c.formData.inFrame?d.forEachFrame({each:function(a,b){return a.LPSiteNotification.formExists(c.formData,function(a){c.formExists=c.formExists||a;b()})},done:e}):d.getTop().LPSiteNotification.formExists(c.formData,
function(a){c.formExists=a;e()})}else a.callback(c.getSiteNotificationData(b))};e.prototype.clear=function(){this.previousTabState&&(this.previousTabState.clear(),delete this.previousTabState);delete this.formData;delete this.password;delete this.generatedPassword};e.prototype.setGeneratedPassword=function(a,b){this.generatedPassword=a;this.generatedURL=b.tabURL};e.prototype.processBasicAuthentication=function(a){this.formData={basicAuthentication:!0,url:a.url,realm:a.realm};this.username=a.username;
this.password=a.password};var f=function(a,b){if(a){var c;c=lp_gettld_url(a.tabURL);if(LPContentScriptFeatures.new_save_site)c=!hasNeverSave(a.tabURL,c);else{var d=IntroTutorial.getState();c=d.enabled&&d.domain===c}c&&(c=j[a.tabID],c&&c.domain===lp_gettld_url(a.tabURL)||(d=j[a.tabID]=new e(a),d.previousTabState=c,c=d),b(c))}else LPPlatform.getCurrentTab(function(a){f(a,b)})};return{getSiteNotification:function(a,b){f(b,function(c){c.getSiteNotification(a,b)})},clear:function(a){f(a,function(a){a.clear()})},
processPasswordSubmit:function(a,b){f(b,function(c){c.processPasswordSubmit(a.formData,b);c.getSiteNotification({callback:a.callback,source:b},b)})},processUsernameSubmit:function(a,b){f(b,function(b){b.processUsernameSubmit(a)})},setGeneratedPassword:function(a,b){f(b,function(c){c.setGeneratedPassword(a,b)})},processBasicAuthentication:function(a,b){f(b,function(b){b.processBasicAuthentication(a)})}}}();
